### ISSUE TITLE
newegg general api problem

### ISSUE THREAD

**Issue by carsonwright** [chrismagnacca/newegg-api#1]
I can't seem to get this to work, the gem doesn't seem to be included in my code, is there anything I'm missing?

**Comment by chrismagnacca** [comment]
My apologies for missing that there was an issue listed; if this is still a problem, how are you referencing the gem in your Gemfile? You will have to reference the git repository as I haven't pushed this to rubygems yet. The command below should fix your issues in your Gemfile, please let me know if it does not. I updated the README.md to reflect this as previously I did not include the :git tag line for inclusion.

gem 'newegg', :git => 'git://github.com/chrismagnacca/newegg-api.git'
